var PS4_PRODUCT_DATA = [
    {
      "position.page": 1,
      "position.position": 1,
      "position.global_position": 1,
      "asin": "B08CKR6M86",
      "price.discounted": true,
      "price.current_price": 89.99,
      "price.currency": "USD",
      "price.before_price": 109.99,
      "price.savings_amount": 20,
      "price.savings_percent": 18.18,
      "reviews.total_reviews": 43,
      "reviews.rating": 4.3,
      "url": "https://www.amazon.com/dp/B08CKR6M86",
      "score": 184.9,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - Far Cry 6 PlayStation 4 Gold Steelbook Edition with free upgrade to the digital PS5 version",
      "thumbnail": "https://m.media-amazon.com/images/I/91GLLEp9yOL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 2,
      "position.global_position": 2,
      "asin": "B074LRF639",
      "price.discounted": false,
      "price.current_price": 524,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 7290,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B074LRF639",
      "score": 34992,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": true,
      "amazonPrime": false,
      "title": "PlayStation 4 Console - 1TB Slim Edition",
      "thumbnail": "https://m.media-amazon.com/images/I/715RBdgZtHL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 3,
      "position.global_position": 3,
      "asin": "B077QT6K94",
      "price.discounted": false,
      "price.current_price": 0,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 2911,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B077QT6K94",
      "score": 13972.8,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "SONY PlayStation 4 Slim 1TB Console, Light & Slim PS4 System, 1TB Hard Drive, All the Greatest Games, TV, Music & More",
      "thumbnail": "https://m.media-amazon.com/images/I/61OL2zIliML._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 4,
      "position.global_position": 4,
      "asin": "B08232YKXB",
      "price.discounted": false,
      "price.current_price": 649.99,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 966,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B08232YKXB",
      "score": 4540.2,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Newest Flagship Sony Play Station 4 1TB HDD Only on Playstation PS4 Console Slim Bundle - Included 3X Games (The Last of U...",
      "thumbnail": "https://m.media-amazon.com/images/I/71ZrwxeXnXL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 5,
      "position.global_position": 5,
      "asin": "B07HHW8C4V",
      "price.discounted": false,
      "price.current_price": 0,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 2588,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B07HHW8C4V",
      "score": 12163.6,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "PlayStation 4 Slim 1TB Console - Marvel's Spider-Man Bundle [Discontinued]",
      "thumbnail": "https://m.media-amazon.com/images/I/711xGPcLL2L._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 6,
      "position.global_position": 6,
      "asin": "B01M0RU6LY",
      "price.discounted": false,
      "price.current_price": 539,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 1674,
      "reviews.rating": 4.6,
      "url": "https://www.amazon.com/dp/B01M0RU6LY",
      "score": 7700.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "PlayStation 4 Slim 500GB Console [Discontinued]",
      "thumbnail": "https://m.media-amazon.com/images/I/71PGvPXpk5L._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 7,
      "position.global_position": 7,
      "asin": "B07MLWLYCN",
      "price.discounted": false,
      "price.current_price": 899.9,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 766,
      "reviews.rating": 4.5,
      "url": "https://www.amazon.com/dp/B07MLWLYCN",
      "score": 3447,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sony PlayStation 4 Pro 1TB White (PS4)",
      "thumbnail": "https://m.media-amazon.com/images/I/71NyRR72fWL._AC_UL320_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 8,
      "position.global_position": 8,
      "asin": "B07VJWMQ5T",
      "price.discounted": false,
      "price.current_price": 0,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 4364,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B07VJWMQ5T",
      "score": 20947.2,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "PlayStation 4 Slim 1TB Console - Fortnite Bundle",
      "thumbnail": "https://m.media-amazon.com/images/I/71uPr4KromL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 9,
      "position.global_position": 9,
      "asin": "B07RLWTXKG",
      "price.discounted": true,
      "price.current_price": 24.99,
      "price.currency": "USD",
      "price.before_price": 39.99,
      "price.savings_amount": 15,
      "price.savings_percent": 37.51,
      "reviews.total_reviews": 5449,
      "reviews.rating": 3.8,
      "url": "https://www.amazon.com/dp/B07RLWTXKG",
      "score": 20706.2,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": true,
      "amazonPrime": false,
      "title": "MOVONE Wireless Controller Dual Vibration Game Joystick Controller for PS4/ Slim/Pro,Compatible with PS4 Console (White+Bl...",
      "thumbnail": "https://m.media-amazon.com/images/I/51JK1ma1YXL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 3,
      "position.global_position": 12,
      "asin": "B01LOP8EZC",
      "price.discounted": false,
      "price.current_price": 0,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 11842,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B01LOP8EZC",
      "score": 55657.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "PlayStation 4 Pro 1TB Console",
      "thumbnail": "https://m.media-amazon.com/images/I/6118ctEjpoL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 4,
      "position.global_position": 13,
      "asin": "B07K14XKZH",
      "price.discounted": false,
      "price.current_price": 0,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 3664,
      "reviews.rating": 4.6,
      "url": "https://www.amazon.com/dp/B07K14XKZH",
      "score": 16854.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sony PlayStation 4 Pro 1TB Console - Black (PS4 Pro)",
      "thumbnail": "https://m.media-amazon.com/images/I/71jN27mYlhL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 5,
      "position.global_position": 14,
      "asin": "B098G9M9ZN",
      "price.discounted": true,
      "price.current_price": 39.82,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 20.17,
      "price.savings_percent": 33.62,
      "reviews.total_reviews": 177,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B098G9M9ZN",
      "score": 849.6,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Ghost of Tsushima Director's Cut - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/81oNHTAsyPS._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 6,
      "position.global_position": 15,
      "asin": "B098Y94S29",
      "price.discounted": true,
      "price.current_price": 29.99,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 30,
      "price.savings_percent": 50.01,
      "reviews.total_reviews": 642,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B098Y94S29",
      "score": 3017.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": true,
      "amazonPrime": false,
      "title": "NBA 2K22 - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/814IztfQ5LL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 7,
      "position.global_position": 16,
      "asin": "B096WVJ9Q4",
      "price.discounted": true,
      "price.current_price": 29.99,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 30,
      "price.savings_percent": 50.01,
      "reviews.total_reviews": 61,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B096WVJ9Q4",
      "score": 286.7,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Marvel’s Guardians of the Galaxy - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/81cgn7LQuUL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 8,
      "position.global_position": 17,
      "asin": "B08L93C4KV",
      "price.discounted": true,
      "price.current_price": 19.99,
      "price.currency": "USD",
      "price.before_price": 39.99,
      "price.savings_amount": 20,
      "price.savings_percent": 50.01,
      "reviews.total_reviews": 570,
      "reviews.rating": 4.6,
      "url": "https://www.amazon.com/dp/B08L93C4KV",
      "score": 2622,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Five Nights at Freddy's: The Core Collection (PS4) - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/81zyNAYCt8S._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 9,
      "position.global_position": 18,
      "asin": "B07SFZX5CH",
      "price.discounted": true,
      "price.current_price": 14.99,
      "price.currency": "USD",
      "price.before_price": 39.99,
      "price.savings_amount": 25,
      "price.savings_percent": 62.52,
      "reviews.total_reviews": 7822,
      "reviews.rating": 4.4,
      "url": "https://www.amazon.com/dp/B07SFZX5CH",
      "score": 34416.8,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Marvel's Avengers for PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/81DugevkxJL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 10,
      "position.global_position": 19,
      "asin": "B087XTT5GZ",
      "price.discounted": true,
      "price.current_price": 19.99,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 40,
      "price.savings_percent": 66.68,
      "reviews.total_reviews": 11942,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B087XTT5GZ",
      "score": 56127.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Assassin’s Creed Valhalla PlayStation 4 Standard Edition with Free Upgrade to the Digital PS5 Version",
      "thumbnail": "https://m.media-amazon.com/images/I/819zQmqyDcL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 11,
      "position.global_position": 21,
      "asin": "B079JCLPBC",
      "price.discounted": false,
      "price.current_price": 123.08,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 5169,
      "reviews.rating": 4.6,
      "url": "https://www.amazon.com/dp/B079JCLPBC",
      "score": 23777.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Playstation Move Twin Pack (PS4)",
      "thumbnail": "https://m.media-amazon.com/images/I/51L9q84-NnS._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 12,
      "position.global_position": 22,
      "asin": "B07YLDNTKB",
      "price.discounted": false,
      "price.current_price": 0,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 8618,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B07YLDNTKB",
      "score": 41366.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "PlayStation 4 Slim 1TB Console - Only On PlayStation Bundle",
      "thumbnail": "https://m.media-amazon.com/images/I/814Cwlg1JaL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 13,
      "position.global_position": 23,
      "asin": "B07D5M7SNW",
      "price.discounted": false,
      "price.current_price": 569.99,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 85,
      "reviews.rating": 4,
      "url": "https://www.amazon.com/dp/B07D5M7SNW",
      "score": 340,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "PlayStation 4 500GB Console (Renewed)",
      "thumbnail": "https://m.media-amazon.com/images/I/51EMRcSgITL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 14,
      "position.global_position": 24,
      "asin": "B07NDCL3XB",
      "price.discounted": false,
      "price.current_price": 189.9,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 5761,
      "reviews.rating": 4.1,
      "url": "https://www.amazon.com/dp/B07NDCL3XB",
      "score": 23620.1,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "NACON Controller Esports Revolution Unlimited Pro V3 PS4 Playstation 4 / PC - Wireless/Wired - Nacon-311608",
      "thumbnail": "https://m.media-amazon.com/images/I/71Xh3jA2emL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 15,
      "position.global_position": 25,
      "asin": "B08P4GMS66",
      "price.discounted": false,
      "price.current_price": 19.86,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 50,
      "reviews.rating": 4.2,
      "url": "https://www.amazon.com/dp/B08P4GMS66",
      "score": 210,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - PS4 Controller Keyboard RALAN，PS4 Wireless Mini Bluetooth Keyboard Gamepad Chatpad Message Keyboard for Pla...",
      "thumbnail": "https://m.media-amazon.com/images/I/6124KHWqHkL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 16,
      "position.global_position": 26,
      "asin": "B01L8QHXJA",
      "price.discounted": true,
      "price.current_price": 37.74,
      "price.currency": "USD",
      "price.before_price": 39.99,
      "price.savings_amount": 2.25,
      "price.savings_percent": 5.63,
      "reviews.total_reviews": 29177,
      "reviews.rating": 4.1,
      "url": "https://www.amazon.com/dp/B01L8QHXJA",
      "score": 119625.7,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Collective Minds Strike Pack F.P.S. Dominator Controller Adapter with MODS & Paddles for PS4",
      "thumbnail": "https://m.media-amazon.com/images/I/71LivfRjtSL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 17,
      "position.global_position": 27,
      "asin": "B079YL9F5T",
      "price.discounted": false,
      "price.current_price": 199.97,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 4286,
      "reviews.rating": 4.5,
      "url": "https://www.amazon.com/dp/B079YL9F5T",
      "score": 19287,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sony PlayStation Gold Wireless Headset 7.1 Surround Sound PS4 New Version 2018",
      "thumbnail": "https://m.media-amazon.com/images/I/51pAMXOam0L._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 18,
      "position.global_position": 28,
      "asin": "B07PR2PKFC",
      "price.discounted": false,
      "price.current_price": 9.85,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 2989,
      "reviews.rating": 4.5,
      "url": "https://www.amazon.com/dp/B07PR2PKFC",
      "score": 13450.5,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "[2 Pack 10FT] 6amLifestyle PS4 Controller Charging Cable, Charge and Play, Micro USB Charger High Speed Data Sync Cord for...",
      "thumbnail": "https://m.media-amazon.com/images/I/71i0M1S3-cL._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 19,
      "position.global_position": 29,
      "asin": "B071CV8CG2",
      "price.discounted": false,
      "price.current_price": 0,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 13824,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B071CV8CG2",
      "score": 66355.2,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "PlayStation 4 Slim 1TB Console",
      "thumbnail": "https://m.media-amazon.com/images/I/61n-yWHcmSS._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 21,
      "position.global_position": 31,
      "asin": "B07D6CC7F7",
      "price.discounted": false,
      "price.current_price": 9.99,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 729,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B07D6CC7F7",
      "score": 3426.3,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - Monzlteck New Wall Mount For PS4 Controller(DualShock 4),Custom Design,Screw-Free Application（Single）",
      "thumbnail": "https://m.media-amazon.com/images/I/61h4NZqOE2S._AC_UY218_.jpg"
    },
    {
      "position.page": 1,
      "position.position": 22,
      "position.global_position": 32,
      "asin": "B095C42KYH",
      "price.discounted": false,
      "price.current_price": 459.99,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 31,
      "reviews.rating": 4.2,
      "url": "https://www.amazon.com/dp/B095C42KYH",
      "score": 130.2,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - 4k Portable Touchscreen Monitor, 15.6\" 100% Adobe 10bit Auto-Rotating UHD Computer Monitor with Dual Speake...",
      "thumbnail": "https://m.media-amazon.com/images/I/81zZzwnCMXL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 11,
      "position.global_position": 33,
      "asin": "B08GXD4L2V",
      "price.discounted": false,
      "price.current_price": 12.99,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 400,
      "reviews.rating": 4.1,
      "url": "https://www.amazon.com/dp/B08GXD4L2V",
      "score": 1640,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - Paddles for PS4 Controller,IWGAME Controller Back Button Attachment",
      "thumbnail": "https://m.media-amazon.com/images/I/51aneKOBztL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 12,
      "position.global_position": 34,
      "asin": "B09H2CDMDR",
      "price.discounted": false,
      "price.current_price": 23.99,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 5,
      "reviews.rating": 5,
      "url": "https://www.amazon.com/dp/B09H2CDMDR",
      "score": 25,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - ORDA Wireless Game Controller Compatible with PS4/PS-4 Pro/PC- White",
      "thumbnail": "https://m.media-amazon.com/images/I/51mW3PcPuuL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 13,
      "position.global_position": 35,
      "asin": "B098KVCFM8",
      "price.discounted": true,
      "price.current_price": 27.99,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 32,
      "price.savings_percent": 53.34,
      "reviews.total_reviews": 125,
      "reviews.rating": 4.7,
      "url": "https://www.amazon.com/dp/B098KVCFM8",
      "score": 587.5,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "FIFA 22 - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/81Phxg79cIL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 14,
      "position.global_position": 36,
      "asin": "B08HTHJ9L2",
      "price.discounted": true,
      "price.current_price": 29.99,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 30,
      "price.savings_percent": 50.01,
      "reviews.total_reviews": 12,
      "reviews.rating": 4.2,
      "url": "https://www.amazon.com/dp/B08HTHJ9L2",
      "score": 50.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Riders Republic PlayStation 4 Standard Edition with free upgrade to the digital PS5 version",
      "thumbnail": "https://m.media-amazon.com/images/I/81wKskUsvzL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 15,
      "position.global_position": 37,
      "asin": "B09GVJT74H",
      "price.discounted": false,
      "price.current_price": 33.99,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 3335,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B09GVJT74H",
      "score": 16008,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "CZN Replacement for PS4 Controller, Compatible with PS4/Pro/Slim, Gamepad/Joystick Intended for Wireless PS4 Controller (red)",
      "thumbnail": "https://m.media-amazon.com/images/I/61lsZx6IBQL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 16,
      "position.global_position": 38,
      "asin": "B09D23785P",
      "price.discounted": true,
      "price.current_price": 27.99,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 32,
      "price.savings_percent": 53.34,
      "reviews.total_reviews": 48,
      "reviews.rating": 4.4,
      "url": "https://www.amazon.com/dp/B09D23785P",
      "score": 211.2,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "NHL 22 - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/51TWJQFNiRL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 17,
      "position.global_position": 39,
      "asin": "B08QFXCNNZ",
      "price.discounted": true,
      "price.current_price": 29.83,
      "price.currency": "USD",
      "price.before_price": 49.99,
      "price.savings_amount": 20.16,
      "price.savings_percent": 40.33,
      "reviews.total_reviews": 860,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B08QFXCNNZ",
      "score": 4128,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Marvel's Spider-Man: Miles Morales - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/71LZm8RQ8LL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 18,
      "position.global_position": 40,
      "asin": "B09742GFC2",
      "price.discounted": true,
      "price.current_price": 19.99,
      "price.currency": "USD",
      "price.before_price": 39.99,
      "price.savings_amount": 20,
      "price.savings_percent": 50.01,
      "reviews.total_reviews": 101,
      "reviews.rating": 4.1,
      "url": "https://www.amazon.com/dp/B09742GFC2",
      "score": 414.1,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Big Rumble Boxing: Creed Champions - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/81XEkiowbsL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 19,
      "position.global_position": 41,
      "asin": "B0998JW6J5",
      "price.discounted": true,
      "price.current_price": 69.99,
      "price.currency": "USD",
      "price.before_price": 99.99,
      "price.savings_amount": 30,
      "price.savings_percent": 30,
      "reviews.total_reviews": 123,
      "reviews.rating": 4.8,
      "url": "https://www.amazon.com/dp/B0998JW6J5",
      "score": 590.4,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "NBA 2K22 75th Anniversary Edition - PlayStation 4",
      "thumbnail": "https://m.media-amazon.com/images/I/9120gFb5FMS._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 20,
      "position.global_position": 42,
      "asin": "B08CKPR8TN",
      "price.discounted": true,
      "price.current_price": 39.99,
      "price.currency": "USD",
      "price.before_price": 59.99,
      "price.savings_amount": 20,
      "price.savings_percent": 33.34,
      "reviews.total_reviews": 358,
      "reviews.rating": 4.4,
      "url": "https://www.amazon.com/dp/B08CKPR8TN",
      "score": 1575.2,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Far Cry 6 PlayStation 4 Standard Edition with Free Upgrade to the Digital PS5 Version",
      "thumbnail": "https://m.media-amazon.com/images/I/81iAa2JPOiL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 21,
      "position.global_position": 43,
      "asin": "B08P4GMS66",
      "price.discounted": false,
      "price.current_price": 19.86,
      "price.currency": "USD",
      "price.before_price": 0,
      "price.savings_amount": 0,
      "price.savings_percent": 0,
      "reviews.total_reviews": 50,
      "reviews.rating": 4.2,
      "url": "https://www.amazon.com/dp/B08P4GMS66",
      "score": 210,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - PS4 Controller Keyboard RALAN，PS4 Wireless Mini Bluetooth Keyboard Gamepad Chatpad Message Keyboard for Pla...",
      "thumbnail": "https://m.media-amazon.com/images/I/6124KHWqHkL._AC_UY218_.jpg"
    },
    {
      "position.page": 2,
      "position.position": 22,
      "position.global_position": 44,
      "asin": "B08CKR6M86",
      "price.discounted": true,
      "price.current_price": 89.99,
      "price.currency": "USD",
      "price.before_price": 109.99,
      "price.savings_amount": 20,
      "price.savings_percent": 18.18,
      "reviews.total_reviews": 43,
      "reviews.rating": 4.3,
      "url": "https://www.amazon.com/dp/B08CKR6M86",
      "score": 184.9,
      "sponsored": false,
      "amazonChoice": false,
      "bestSeller": false,
      "amazonPrime": false,
      "title": "Sponsored Ad - Far Cry 6 PlayStation 4 Gold Steelbook Edition with free upgrade to the digital PS5 version",
      "thumbnail": "https://m.media-amazon.com/images/I/91GLLEp9yOL._AC_UY218_.jpg"
    }
   ]

exports.PS4_PRODUCT_DATA = PS4_PRODUCT_DATA;